esphome:
  name: nspanel_office
  comment: NSPanel Office

substitutions:
  wifi_ssid_var: !secret wifi_ssid
  wifi_password_var: !secret wifi_password
  ota_password: !secret wifi_password

  # sensors
  sensor_entity_windows: binary_sensor.windows
  sensor_entity_room_temp: sensor.climate_livingroom_temperature
  sensor_entity_room_humidity: sensor.climate_livingroom_humidity
  sensor_entity_weather_temp: weather.forecast_home # use attribute temperature
  sensor_entity_weather_rain: empty.empty
  sensor_entity_weather_state: weather.forecast_home # use state

  sensor_entity_heating_temp: climate.heizung_buro # use attribute temperature
  sensor_entity_heating_enable: climate.heizung_buro
  sensor_entity_blinds_position: cover.blinds_office_cover

  # hardware buttons
  hwbtn_left: "Solder/ Lab Power"
  hwbtn_right: "Good Morning"

  hwbtn_left_short_ent: "switch.office_lab_soldering_iron"
  hwbtn_left_short_srv: "switch.toggle"
  hwbtn_left_long_ent: "scene.office_lab_lab_powersupply"
  hwbtn_left_long_srv: "switch.toggle"

  hwbtn_right_short_ent: "script.good_morning"
  hwbtn_right_short_srv: "script.good_morning"
  hwbtn_right_long_ent: "script.good_morning"
  hwbtn_right_long_srv: "script.good_morning"

  # Scene Buttons & Icons
  btn_scn11_txt: "All Off"
  btn_scn11_ico: "l"
  btn_scn11_ent: "scene.alles_aus_2"
  btn_scn11_srv: "scene.turn_on"

  btn_scn12_txt: "Gaming"
  btn_scn12_ico: "s"
  btn_scn12_ent: "scene.buro_gaming"
  btn_scn12_srv: "scene.turn_on"

  btn_scn13_txt: "Conference"
  btn_scn13_ico: "U"
  btn_scn13_ent: "scene.video_call"
  btn_scn13_srv: "scene.turn_on"

  btn_scn14_txt: "Evening"
  btn_scn14_ico: "O"
  btn_scn14_ent: "scene.buro_arbeiten_tag_2"
  btn_scn14_srv: "scene.turn_on"

  btn_scn15_txt: "Working"
  btn_scn15_ico: "N"
  btn_scn15_ent: "scene.buro_working"
  btn_scn15_srv: "scene.turn_on"

  btn_scn16_txt: ""
  btn_scn16_ico: ""
  btn_scn16_ent: "empty.empty"
  btn_scn16_srv: "scene.turn_on"

  btn_scn17_txt: ""
  btn_scn17_ico: ""
  btn_scn17_ent: "empty.empty"
  btn_scn17_srv: "scene.turn_on"

  btn_scn18_txt: ""
  btn_scn18_ico: ""
  btn_scn18_ent: "empty.empty"
  btn_scn18_srv: "scene.turn_on"

  btn_scn21_txt: ""
  btn_scn21_ico: ""
  btn_scn21_ent: "empty.empty"
  btn_scn21_srv: "scene.turn_on"

  btn_scn22_txt: ""
  btn_scn22_ico: ""
  btn_scn22_ent: "empty.empty"
  btn_scn22_srv: "scene.turn_on"

  btn_scn23_txt: ""
  btn_scn23_ico: ""
  btn_scn23_ent: "empty.empty"
  btn_scn23_srv: "scene.turn_on"

  btn_scn24_txt: ""
  btn_scn24_ico: ""
  btn_scn24_ent: "empty.empty"
  btn_scn24_srv: "scene.turn_on"

  btn_scn25_txt: ""
  btn_scn25_ico: ""
  btn_scn25_ent: "empty.empty"
  btn_scn25_srv: "scene.turn_on"

  btn_scn26_txt: ""
  btn_scn26_ico: ""
  btn_scn26_ent: "empty.empty"
  btn_scn26_srv: "scene.turn_on"

  btn_scn27_txt: ""
  btn_scn27_ico: ""
  btn_scn27_ent: "empty.empty"
  btn_scn27_srv: "scene.turn_on"

  btn_scn28_txt: ""
  btn_scn28_ico: ""
  btn_scn28_ent: "empty.empty"
  btn_scn28_srv: "scene.turn_on"

  btn_misc1_txt: "Soldering"
  btn_misc1_ico: "u"
  btn_misc1_ent: "switch.office_lab_soldering_iron"
  btn_misc1_srv: "switch.toggle"

  btn_misc2_txt: "Lab Power"
  btn_misc2_ico: "X"
  btn_misc2_ent: "switch.office_lab_lab_powersupply"
  btn_misc2_srv: "switch.toggle"

  btn_misc3_txt: "Dashboard"
  btn_misc3_ico: "S"
  btn_misc3_ent: "switch.uhr_buro"
  btn_misc3_srv: "switch.toggle"

  btn_misc4_txt: "Laptop"
  btn_misc4_ico: "J"
  btn_misc4_ent: "switch.mixer_laptop_arbeit"
  btn_misc4_srv: "switch.toggle"

  btn_misc5_txt: "Manual"
  btn_misc5_ico: "y"
  btn_misc5_ent: "input_boolean.manual_mode_office"
  btn_misc5_srv: "input_boolean.toggle"

  btn_misc6_txt: ""
  btn_misc6_ico: ""
  btn_misc6_ent: "empty.empty"
  btn_misc6_srv: "switch.toggle"

  btn_misc7_txt: ""
  btn_misc7_ico: ""
  btn_misc7_ent: "empty.empty"
  btn_misc7_srv: "switch.toggle"

  btn_misc8_txt: ""
  btn_misc8_ico: ""
  btn_misc8_ent: "empty.empty"
  btn_misc8_srv: "switch.toggle"

  btn_clim1_txt: "Fan"
  btn_clim1_ico: "R"
  btn_clim1_ent: "switch.fan"
  btn_clim1_srv: "switch.toggle"

  btn_clim2_txt: ""
  btn_clim2_ico: ""
  btn_clim2_ent: "empty.empty"
  btn_clim2_srv: "switch.toggle"

  btn_clim3_txt: ""
  btn_clim3_ico: ""
  btn_clim3_ent: "empty.empty"
  btn_clim3_srv: "switch.toggle"

  btn_clim4_txt: ""
  btn_clim4_ico: ""
  btn_clim4_ent: "empty.empty"
  btn_clim4_srv: "switch.toggle"

  info_text: 'Guest Wifi<br/>SSID: GuestWifi\nPassword: 12345678'
  info_qr: "wifi:S:/dev/guests;T:WPA;P:flyMeToTheMoon;H:false;;"

<<: !include includes/_index.yaml
