esphome:
  name: nspanel_office
  comment: NSPanel Office

substitutions:
  devicename: "testdevice"
  button_left_text: "Night/ Day Mode"
  wifi_ssid_var: !secret wifi_ssid
  wifi_password_var: !secret wifi_password
  ota_password: !secret wifi_password

<<: !include includes/_index.yaml
