esphome:
  name: livingroom
  comment: Living room ESP32 controller
  area: Living Room

substitutions:
  devicename: "testdevice"
  button_left_text: "Night/ Day Mode"

<<: !include includes/_index.yaml
