switch:
  - name: Nextion display - Power
    platform: gpio
    id: screen_power
    entity_category: diagnostic
    pin:
      number: 4
      inverted: true
    restore_mode: ALWAYS_ON
    internal: true
    disabled_by_default: false

esphome:
  on_boot:
    - priority: 600.0 # This is where most sensors are set up.
      then:
        - wait_until:
            condition:
              - lambda: return disp->is_setup();
            timeout: 5s
        - if:
            condition:
              - lambda: return (not disp->is_detected());
            then:
              - switch.turn_off: screen_power
              - delay: 2s
              - switch.turn_on: screen_power
