<<: !include _defaults.yaml

esphome:
  min_version: 2023.12.0
  platformio_options:
    build_flags:
      - -Wno-missing-field-initializers
      - -D NSPANEL_HA_BLUEPRINT_CORE

esp32:
  board: esp32dev
  framework:
    type: esp-idf

api:
  reboot_timeout: 60min

ota:
  id: ota_std
  password: ${ota_password}
  safe_mode: true
  reboot_timeout: 3min
  num_attempts: 3

web_server:
  port: 80

logger:
  level: DEBUG
  logs:
    sensor: WARN
    resistance: WARN
    text_sensor: WARN
    ntc: WARN

##### External components #####
external_components:
  - source:
      # type: local
      # path: packages/Blackymas/components
      type: git
      url: https://github.com/Blackymas/NSPanel_HA_Blueprint
      ref: v4.3.7
    components:
      - nspanel_ha_blueprint
    refresh: 300s
  - source:
      type: git
      url: https://github.com/edwardtfn/esphome
      ref: nextion-v435
    components:
      - nextion # Change this when that PR#6192 gets released (2024.5?)
      - psram # Change this when that PR#6526 gets released (2024.5?)
    refresh: 300s
  - source:
      type: git
      url: https://github.com/edwardtfn/esphome
      ref: esp32ble-01
    components:
      - esp32_ble_tracker # Change this when that PR#6585 gets released (2024.5?)
    refresh: 300s
  - source:
      type: git
      url: https://github.com/edwardtfn/esphome
      ref: adc-sampling
    components:
      - adc # Change this when PR#6330 is merged (2024.4?)
    refresh: 300s

psram:
  id: ext_ram

nspanel_ha_blueprint:

sensor:
  ##### Uptime #####
  - platform: uptime
    name: Uptime
    disabled_by_default: true

packages:
  # Includes Wifi and Wifi Status Updates
  wifi: !include wifi.yaml

  # Includes the Hardware Relays as Home Assistant Switches
  relays: !include relays.yaml

  # Includes the Hardware Buttons as Home Assistant that publish to MQTT
  buttons: !include buttons.yaml

  # Includes the Display and Display Logic including touch switches that publish to MQTT
  display: !include display/_index.yaml

  # Includes the notification speaker
  speaker: !include speaker.yaml

  # Includes the onboard sensors
  sensors: !include sensors.yaml

  # # Includes miscalaneous, e.g. reboot
  # misc: !include misc.yaml
