binary_sensor:
  - platform: gpio
    id: hw_btn_left
    pin:
      number: 14
      inverted: true
    filters:
      - delayed_on: 50ms
    on_click: !include
      file: templates/touch_short_long.yaml
      vars:
        button_set: hw_btn_left

  - platform: gpio
    id: hw_btn_right
    pin:
      number: 27
      inverted: true
    filters:
      - delayed_on: 50ms
    on_click: !include
      file: templates/touch_short_long.yaml
      vars:
        button_set: hw_btn_right
