sensor:
  # taken from https://github.com/Blackymas/NSPanel_HA_Blueprint
  ##### INTERNAL TEMPERATURE SENSOR, ADC VALUE #####
  - id: ntc_source
    platform: adc
    pin: 38
    attenuation: 11db
    # samples: 4
    update_interval: 10s
    filters:
      - sliding_window_moving_average:
          send_every: 2
          window_size: 7

  ##### INTERNAL TEMPERATURE SENSOR, adc reading converted to resistance (calculation)#####
  - id: resistance_sensor
    platform: resistance
    sensor: ntc_source
    configuration: DOWNSTREAM
    resistor: 11.2kOhm

  ##### INTERNAL TEMPERATURE SENSOR, resistance to temperature (calculation) #####
  - id: temp_nspanel
    name: Temperature
    platform: ntc
    sensor: resistance_sensor
    unit_of_measurement: °C
    internal: false
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    # filters:
    #   - lambda: |-
    #       return x + temperature_correction->state;
    # on_value:
    #   then:
    # Show panel's temperature if API or Wi-Fi are out
    # - lambda: display_embedded_temp->execute();

    ###### Display Brightness GET VALUE FROM NSPanel SLIDER #####
  # - id: brightslider
  #   name: brightness Slider
  #   platform: nextion
  #   variable_name: brightslider
  #   internal: true
  #   on_value:
  #     then:
  #       - number.set:
  #           id: display_brightness
  #           value: !lambda return int(x);
  #       - lambda: |-
  #           timer_reset_all->execute();
