binary_sensor:
  - platform: template
    name: Touch Scene 1.1
    id: touch_scene_1_1
  - platform: template
    name: Touch Scene 1.2
    id: touch_scene_1_2
  - platform: template
    name: Touch Scene 1.3
    id: touch_scene_1_3
  - platform: template
    name: Touch Scene 1.4
    id: touch_scene_1_4
  - platform: template
    name: Touch Scene 1.5
    id: touch_scene_1_5
  - platform: template
    name: Touch Scene 1.6
    id: touch_scene_1_6
  - platform: template
    name: Touch Scene 1.7
    id: touch_scene_1_7
  - platform: template
    name: Touch Scene 1.8
    id: touch_scene_1_8
  - platform: template
    name: Touch Scene 2.1
    id: touch_scene_2_1
  - platform: template
    name: Touch Scene 2.2
    id: touch_scene_2_2
  - platform: template
    name: Touch Scene 2.3
    id: touch_scene_2_3
  - platform: template
    name: Touch Scene 2.4
    id: touch_scene_2_4
  - platform: template
    name: Touch Scene 2.5
    id: touch_scene_2_5
  - platform: template
    name: Touch Scene 2.6
    id: touch_scene_2_6
  - platform: template
    name: Touch Scene 2.7
    id: touch_scene_2_7
  - platform: template
    name: Touch Scene 2.8
    id: touch_scene_2_8
  - platform: template
    name: Touch Climate 1
    id: touch_climate_1
  - platform: template
    name: Touch Climate 2
    id: touch_climate_2
  - platform: template
    name: Touch Climate 3
    id: touch_climate_3
  - platform: template
    name: Touch Climate 4
    id: touch_climate_4
  - platform: template
    name: Touch Misc 1
    id: touch_misc_1
  - platform: template
    name: Touch Misc 2
    id: touch_misc_2
  - platform: template
    name: Touch Misc 3
    id: touch_misc_3
  - platform: template
    name: Touch Misc 4
    id: touch_misc_4
  - platform: template
    name: Touch Misc 5
    id: touch_misc_5
  - platform: template
    name: Touch Misc 6
    id: touch_misc_6
  - platform: template
    name: Touch Misc 7
    id: touch_misc_7
  - platform: template
    name: Touch Misc 8
    id: touch_misc_8
