wifi:
  id: wifi_component
  power_save_mode: LIGHT
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  on_connect:
    then:
      - script.execute: refresh_wifi_icon
  on_disconnect:
    then:
      - script.execute: refresh_wifi_icon

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    entity_category: "diagnostic"
    update_interval: 10s
    on_value:
      then:
        lambda: |
          if (id(disp).has_nextion()) {
            id(disp).set_component_text("wifi", id(wifi_signal).state);
          }
          if (id(wifi_signal).state < -70) {
            id(disp).set_component_background_color("wifi", 0xFF0000);
          } else if (id(wifi_signal).state < -60) {
            id(disp).set_component_background_color("wifi", 0xFFA500);
          } else {
            id(disp).set_component_background_color("wifi", 0x00FF00);
          }
